[package]
name = "sourccey-sync"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
dirs.workspace = true
fs2.workspace = true
rusqlite.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sourccey-sync-core = { path = "../sourccey-sync-core" }
uuid.workspace = true

